// <auto-generated />
using System;
using ISUAnket.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISUAnket.DataAccess.Migrations
{
    [DbContext(typeof(ISUAnketContext))]
    [Migration("20250617074421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ANKET")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Anket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("AnketDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DuzenlenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DuzenleyenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DuzenleyenKullaniciId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Anketler", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Birimler", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Cevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CevapTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("SoruId");

                    b.ToTable("Cevaplar", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KulaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OturumAcikMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("SonCikisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roller", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("AnketId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DuzenlenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DuzenleyenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SoruSecenekleri")
                        .HasColumnType("text");

                    b.Property<int>("SoruTipi")
                        .HasColumnType("integer");

                    b.Property<int>("VeriTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnketId");

                    b.HasIndex("DuzenleyenKullaniciId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Sorular", "ANKET");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Anket", b =>
                {
                    b.HasOne("ISUAnket.EntityLayer.Entities.Kullanici", "DuzenleyenKullanici")
                        .WithMany()
                        .HasForeignKey("DuzenleyenKullaniciId");

                    b.HasOne("ISUAnket.EntityLayer.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuzenleyenKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Cevap", b =>
                {
                    b.HasOne("ISUAnket.EntityLayer.Entities.Birim", "Birim")
                        .WithMany("Cevaplar")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISUAnket.EntityLayer.Entities.Soru", "Soru")
                        .WithMany("Cevaplar")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Kullanici", b =>
                {
                    b.HasOne("ISUAnket.EntityLayer.Entities.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Soru", b =>
                {
                    b.HasOne("ISUAnket.EntityLayer.Entities.Anket", "Anket")
                        .WithMany("Sorular")
                        .HasForeignKey("AnketId");

                    b.HasOne("ISUAnket.EntityLayer.Entities.Kullanici", "DuzenleyenKullanici")
                        .WithMany()
                        .HasForeignKey("DuzenleyenKullaniciId");

                    b.HasOne("ISUAnket.EntityLayer.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anket");

                    b.Navigation("DuzenleyenKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Anket", b =>
                {
                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Birim", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("ISUAnket.EntityLayer.Entities.Soru", b =>
                {
                    b.Navigation("Cevaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
